---
title: "Projects"
website:
  navbar:
    logo: favicon_big.png
format:
  html: 
    page-layout: full
---

::: panel-tabset
## Statistical/Machine Learning in R

In this project for STAT 551 at Cal Poly, we produced a mock document for the EPA that used machine learning to predict which individuals are at risk of 1) experiencing Alzheimer's and/or 2) having a stroke, in the United States. This project helped bolster my machine learning skills in R, including the most cutting-edge techniques, while also utilizing data visualization and other data summary techniques.

::: panel-tabset
## Python

```{=html}
<iframe width="100%" height="700" src="project_files/FinalReport_py.html" title="Python File"></iframe>
```
## R

```{=html}
<iframe width="100%" height="700" src="project_files/FinalReport_r.html" title="R File"></iframe>
```
:::

## Thesis

My thesis for my Master of Science degree in Statistics at Cal Poly was to analyze the impact of the new Video Assistant Referee (VAR) technology on the world's top soccer league, the English Premier League.

```{=html}
<iframe width="100%" height="700" src="project_files/GEN_CPDS23_Final_Report.pdf" title="GEN Final Report"></iframe>
```
## 

## Analysis of CSU Colleges

My data science senior capstone project at Cal Poly was to create a network analysis framework for [the Global Emancipation Network]() to help combat human trafficking by identifying criminal networks in the illicit massage business industry. I worked on an interdisciplinary team with three other data science students: Bella White, Thea Yang, and Amara Zabback. The project took course over a 6 month period that consisted of comprehensive network planning and design, data collection from various publicly available sources, self-teaching of a graph database and visualization software (Neo4j), and an interactive network implementation.

For a comprehensive summary of the work we completed, please refer to the formal report we created below:

```{=html}
<iframe width="100%" height="700" src="project_files/GEN_CPDS23_Final_Report.pdf" title="GEN Final Report"></iframe>
```
## Oh Hell Project

```{=html}
<iframe id="example1" src="https://tf8s7t-sean0leader.shinyapps.io/oh_hell_statistics" style="border: none; width: 100%; height: 720px" frameborder="0"></iframe>
```
:::
